def draft_pr_with_ai(files):
    """
    Call OpenAI (or your LLM) with commit diffs + company STANDARD.md
    to produce (title, body).
    """
    # TODO: read diffs, load STANDARDS.md, call openai.Completion/ChatCompletion
    return "WIP: AI-drafted PR", "This PR was generated by Beluga"