# -------------------------------------------------------------------
# AI Agent for PR Drafting
# -------------------------------------------------------------------
# What it does:
#   - Builds the prompt combining diffs + STANDARDS.md
#   - Calls OpenAI ChatCompletion to draft PR title & body
#
# What it invokes:
#   - openai.ChatCompletion (or Completion)
#
# Where to add changes:
#   - Under TODO:
#     • Load diff contents
#     • Read STANDARDS.md from repo root
#     • Construct messages list
#     • Parse response for title/body
#
# What not to change:
#   - Function signature draft_pr_with_ai(files)
#

from openai import OpenAI
from dotenv import load_dotenv
import os
class PrAgent:
    def __init__(self):
        # Load token from .env file
        load_dotenv()
        self.apiKey = os.getenv('OPENAI_API_KEY')
        self.customEndpoint = os.getenv('OPENAI_ENDPOINT')
        
        # Create the Azure OpenAI client instance with c3 custom url endpoint given
        self.client = OpenAI(
            api_key=self.apiKey,
            base_url=self.customEndpoint,
            default_headers={"api-version": "2024-11-20"}
        )
    
    def getResponse(self, prompt, model="o1", max_tokens=75):
        # Create a chat to send a prompt and get a response
        print(self.client)
        print(self.customEndpoint)
        response = self.client.chat.completions.create(
            model=model,
            messages=[
                {"role": "user", "content": prompt}
            ],
            max_tokens=max_tokens
        )
        return response.choices[0].message.content.strip()


def draft_pr_with_ai(files):
    """
    Given a list of changed files,
    return a tuple (title, body) drafted by AI.
    """
    # TODO: gather file diffs
    # diffs_text = …
    # TODO: load STANDARDS.md:
    # with open("STANDARDS.md") as f: standards = f.read()
    # TODO: call OpenAI:
    # response = openai.ChatCompletion.create(
    #     model="gpt-4",
    #     messages=[…]
    # )
    return "WIP: AI-drafted PR", "This PR was generated by Beluga…"


# Test the file when ran
if __name__ == "__main__":
    # Usage
    agent = PrAgent()
    response = agent.getResponse("What is the weather like today?")
    print(response)

