# -------------------------------------------------------------------
# AI Agent for PR Drafting
# -------------------------------------------------------------------
# What it does:
#   - Builds the prompt combining diffs + STANDARDS.md
#   - Calls OpenAI ChatCompletion to draft PR title & body
#
# What it invokes:
#   - openai.ChatCompletion (or Completion)
#
# Where to add changes:
#   - Under TODO:
#     • Load diff contents
#     • Read STANDARDS.md from repo root
#     • Construct messages list
#     • Parse response for title/body
#
# What not to change:
#   - Function signature draft_pr_with_ai(files)
#
def draft_pr_with_ai(files):
    """
    Given a list of changed files,
    return a tuple (title, body) drafted by AI.
    """
    # TODO: gather file diffs
    # diffs_text = …
    # TODO: load STANDARDS.md:
    # with open("STANDARDS.md") as f: standards = f.read()
    # TODO: call OpenAI:
    # response = openai.ChatCompletion.create(
    #     model="gpt-4",
    #     messages=[…]
    # )
    return "WIP: AI-drafted PR", "This PR was generated by Beluga…"